/* app-window.h generated by valac 0.56.18-dirty, the Vala compiler, do not modify */

#ifndef __APP_WINDOW_H__
#define __APP_WINDOW_H__

#include <adwaita.h>
#include <glib-object.h>
#include <glib.h>

G_BEGIN_DECLS

#define TPD_TYPE_APP_WINDOW (tpd_app_window_get_type ())
#define TPD_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TPD_TYPE_APP_WINDOW, TpdAppWindow))
#define TPD_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TPD_TYPE_APP_WINDOW, TpdAppWindowClass))
#define TPD_IS_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TPD_TYPE_APP_WINDOW))
#define TPD_IS_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TPD_TYPE_APP_WINDOW))
#define TPD_APP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TPD_TYPE_APP_WINDOW, TpdAppWindowClass))

typedef struct _TpdAppWindow TpdAppWindow;
typedef struct _TpdAppWindowClass TpdAppWindowClass;
typedef struct _TpdAppWindowPrivate TpdAppWindowPrivate;

struct _TpdAppWindow {
	AdwApplicationWindow parent_instance;
	TpdAppWindowPrivate * priv;
};

struct _TpdAppWindowClass {
	AdwApplicationWindowClass parent_class;
};

GType tpd_app_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC(TpdAppWindow, g_object_unref)
TpdAppWindow* tpd_app_window_new (TpdApp* app);
TpdAppWindow* tpd_app_window_construct(GType object_type, TpdApp* app);

G_END_DECLS

#endif