/* app.h generated by valac 0.56.18-dirty, the Vala compiler, do not modify */

#ifndef __APP_H__
#define __APP_H__

#include <adwaita.h>
#include <glib-object.h>
#include <glib.h>

G_BEGIN_DECLS

#define TPD_TYPE_APP (tpd_app_get_type())
#define TPD_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), TPD_TYPE_APP, TpdApp))
#define TPD_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), TPD_TYPE_APP, TpdAppClass))
#define TPD_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), TPD_TYPE_APP))
#define TPD_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), TPD_TYPE_APP))
#define TPD_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), TPD_TYPE_APP, TpdAppClass))

typedef struct _TpdApp TpdApp;
typedef struct _TpdAppClass TpdAppClass;
typedef struct _TpdAppPrivate TpdAppPrivate;

struct _TpdApp {
	AdwApplication parent_instance;
	TpdAppPrivate * priv;
};

struct _TpdAppClass {
	AdwApplicationClass parent_class;
};

GType tpd_app_get_type(void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC(TpdApp, g_object_unref) TpdApp* tpd_app_new(void);

G_END_DECLS

#endif