/* app-window.h generated by valac 0.56.18-dirty, the Vala compiler, do not modify */

#ifndef __WINDOW_H__
#define __WINDOW_H__

#include <adwaita.h>
#include <glib-object.h>
#include <glib.h>

G_BEGIN_DECLS

#define TPD_TYPE_WINDOW (tpd_window_get_type ())
#define TPD_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TPD_TYPE_WINDOW, TpdWindow))
#define TPD_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TPD_TYPE_WINDOW, TpdWindowClass))
#define TPD_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TPD_TYPE_WINDOW))
#define TPD_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TPD_TYPE_WINDOW))
#define TPD_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TPD_TYPE_WINDOW, TpdWindowClass))

typedef struct _TpdWindow TpdWindow;
typedef struct _TpdWindowClass TpdWindowClass;
typedef struct _TpdWindowPrivate TpdWindowPrivate;

struct _TpdWindow {
	AdwApplicationWindow parent_instance;
	TpdWindowPrivate * priv;
};

struct _TpdWindowClass {
	AdwApplicationWindowClass parent_class;
};

GType tpd_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC(TpdWindow, g_object_unref)
TpdWindow* tpd_window_new(TpdApp* app);

G_END_DECLS

#endif